### ISSUE TITLE
Some problems with real-time running with DVXplorer.

### ISSUE THREAD

**Issue by doujiarui** [uzh-rpg/rpg_ultimate_slam_open#3]
Hi, thank you very much for your work being open sourced and for your contributions. 

I used the event camera DVXplorer to run the only Events-IMU mode of Ulitmate SLAM. After modifying the parameters according to your suggestion, I found that the trajectory drifted hugely after running for a period of time. I guess the IMU calibration may not be accurate enough. Sometimes the visualization of the picture is very turbulent. I don't know why.  Do you have any suggestions?

![run](https://user-images.githubusercontent.com/58241591/176624593-9a40530a-737c-4630-8cd1-e7773007b24c.png)

**Comment by DavidNY123** [comment]
Hey, How did you solve this problem?

**Comment by Nemophilist98** [comment]
> Hey, How did you solve this problem?

I calibrated my camera and it worked a lot better.

**Comment by shrutarv** [comment]
Hi,

I am also trying to run ultimate slam with a Dvxplorer + IMU.
When I execute the command:
roslaunch ze_vio_ceres live_DAVIS240C_events_only.launch camera_name:=Dvxplorer_test timeshift_cam_imu:=0.8100209382249794

I get the below error. None of the other steps gave an error to me.
================================================================================REQUIRED process [ze_vio_ceres-1] has died!
process has died [pid 666233, exit code -6, cmd /home/eventcamera/uslam_ws/devel/lib/ze_vio_ceres/ze_vio_ceres_node --data_source=2 # rostopic --vio_use_events=1 --vio_use_events_and_images=0 --vio_rescale_intrinsics_for_distortion=true --timeshift_cam_imu=0.8100209382249794 --calib_filename=/home/eventcamera/uslam_ws/src/rpg_ultimate_slam_open/applications/ze_vio_ceres/../../calibration/DAVIS-IJRR17.yaml --flagfile=/home/eventcamera/uslam_ws/src/rpg_ultimate_slam_open/applications/ze_vio_ceres/cfg/vio_base.conf --flagfile=/home/eventcamera/uslam_ws/src/rpg_ultimate_slam_open/applications/ze_vio_ceres/cfg/vio_davis.conf --data_interval_between_event_packets=33 # events-only pipeline: interval between successive event frames. --data_use_time_interval=true # events-only pipeline: if true, data_interval_between_event_packets is interpreted as milliseconds, otherwise as number of events --data_size_augmented_event_packet=40000 # max number of events per event frame (should be >= vio_frame_size) --vio_frame_size=15000 # each event frame will be drawn with that number of events --vio_do_motion_correction=1 --noise_event_rate=20000 --vio_frame_norm_factor=4.0 --vio_trace_pose=1 --log_dir=/tmp --vmodule=feature_tracker=0 --colorlogtostderr=1 --logtostderr=1 --alsologtostderr=1 --vio_viz_feature_tracks=True --vio_viz_feature_tracks_length=0 __name:=ze_vio_ceres __log:=/home/eventcamera/.ros/log/2b287174-7fb7-11ed-8cf7-13c9a116dde2/ze_vio_ceres-1.log].
log file: /home/eventcamera/.ros/log/2b287174-7fb7-11ed-8cf7-13c9a116dde2/ze_vio_ceres-1*.log
Initiating shutdown!
================================================================================
[log.docx](https://github.com/uzh-rpg/rpg_ultimate_slam_open/files/10267197/log.docx)

Could you please help me with this. How did you manage to run ultimate slam on dvxplorer?

Thank you

**Comment by agelamin** [comment]
@shrutarv I have the same issue did you solve it?
